apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: url-shortener-gitops
  namespace: url-shortener

resources:
  - 00-namespace.yaml
  - 00-secrets.yaml
  - 01-postgres-config.yaml
  - 02-postgres.yaml
  - 03-link-service.yaml
  - 04-redirect-service.yaml
  - 05-stats-service.yaml
  - 07-frontend.yaml
  - simple-ingress.yaml

namespace: url-shortener

images:
  - name: itsbaivab/url-shortener-link
    newTag: latest
  - name: itsbaivab/url-shortener-redirect
    newTag: latest
  - name: itsbaivab/url-shortener-stats
    newTag: latest
  - name: itsbaivab/url-shortener-frontend
    newTag: latest

configMapGenerator:
  - name: app-config
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - DB_MAX_CONNECTIONS=100
      - CACHE_TTL=3600

generatorOptions:
  disableNameSuffixHash: true
